apiVersion: gcp.platform.upbound.io/v1alpha1
kind: XGKE
metadata:
  name: configuration-gcp-gke
spec:
  parameters:
    id: configuration-gcp-gke
    region: us-west2
    version: latest
    nodes:
      count: 1
      instanceType: n1-standard-4
  writeConnectionSecretToRef:
    name: configuration-gcp-gke-kubeconfig
    namespace: upbound-system
