apiVersion: gcp.platform.upbound.io/v1alpha1
kind: GKE
metadata:
  name: configuration-gcp-gke
  namespace: default
spec:
  parameters:
    id: configuration-gcp-gke
    project: test-project-123
    region: us-west2
    version: "1.34"
    nodes:
      count: 1
      machineType: e2-standard-2
