apiVersion: gcp.platform.upbound.io/v1alpha1
kind: GKE
metadata:
  name: configuration-gcp-gke
  namespace: default
spec:
  parameters:
    id: configuration-gcp-gke
    region: us-west2
    version: latest
    nodes:
      count: 1
      instanceType: n1-standard-4
